let CM=null,MEMBERS=[{id:1,name:"许灏",role:"战略规划与项目统筹人",desc:"统筹整体战略、团队分工、进度管控，负责对外对接、全套材料总审核。"},{id:2,name:"赵恩京",role:"产品研发与技术合规负责人",desc:"文献资料查询，具体相关药品学习，核查行业合规标准，提供技术数据支撑。"},{id:3,name:"袁淑星",role:"市场调研与品牌推广负责人",desc:"调研行业竞品与用户需求，规划品牌定位，策划宣传推广、拓展合作客源。"},{id:4,name:"孙铭瑞",role:"渠道运营与用户服务负责人",desc:"维护线上线下合作渠道，处理用户咨询反馈，统计运营数据并复盘优化。"},{id:5,name:"赵淑雅",role:"财务分析与路演展示负责人",desc:"核算收支、规划融资，经营模式思考，负责路演ppt讲解，财务汇报。"}],SK="team6b",D={notes:[],files:[],links:[],tasks:[]}
function LD(){try{let r=localStorage.getItem(SK);if(r)D=JSON.parse(r)}catch(e){}}
function SD(){try{localStorage.setItem(SK,JSON.stringify(D))}catch(e){}}
function toast(m,t){let e=document.getElementById("toast");e.textContent=m;e.className="toast "+t;requestAnimationFrame(()=>e.classList.add("show"));setTimeout(()=>e.classList.remove("show"),2500)}
function M(){document.querySelector(".members").innerHTML=MEMBERS.map(m=>"<div class=\"member-card"+(CM===m.id?" active":"")+"\" onclick=\"setCM("+m.id+")\"><div class=\"member-name\">"+m.name+"</div><div class=\"member-role\">"+m.role+"</div><div class=\"member-desc\">"+m.desc+"</div><span class=\"member-badge\">📌 "+D.notes.filter(n=>n.authorId===m.id).length+"</span><span class=\"member-badge\">📎 "+D.files.filter(f=>f.authorId===m.id).length+"</span><span class=\"member-badge\">✅ "+D.tasks.filter(t=>t.assigneeId===m.id&&!t.done).length+"</span>"+(CM===m.id?"<div style=\"margin-top:6px;font-size:11px;color:var(--accent2)\">▼ 当前空间</div>":"")+"</div>").join("")}
function PS(){["noteAuthor","fileAuthor","linkAuthor","taskAssignee"].forEach(id=>{let e=document.getElementById(id);if(e)e.innerHTML="<option value=\"\">全部成员</option>"+MEMBERS.map(m=>"<option value=\""+m.id+"\">"+m.name+"</option>")})}
function addNote(){let t=document.getElementById("noteTitle").value.trim(),c=document.getElementById("noteContent").value.trim(),a=parseInt(document.getElementById("noteAuthor").value)||null;if(!c){toast("请输入内容","error");return}D.notes.unshift({id:Date.now(),title:t||"无标题",content:c,authorId:a,ct:new Date().toLocaleString()});SD();document.getElementById("noteTitle").value="";document.getElementById("noteContent").value="";RN();M();toast("已添加","success")}
function RN(){let items=D.notes;if(CM)items=items.filter(x=>x.authorId===CM);let s=document.getElementById("noteSearch").value.toLowerCase();if(s)items=items.filter(n=>n.title.toLowerCase().includes(s)||n.content.toLowerCase().includes(s));document.getElementById("noteList").innerHTML=items.length?items.map(n=>"<div class=\"item\"><div class=\"item-info\"><div class=\"item-title\">📌 "+n.title+"</div><div style=\"font-size:12px;color:var(--dim);white-space:pre-wrap\">"+n.content+"</div><div class=\"item-meta\">"+n.ct+" "+(n.authorId?"<span class=\"item-author\">"+MEMBERS.find(m=>m.id===n.authorId).name+"</span>":"")+"</div></div><div class=\"item-actions\"><button class=\"btn btn-sm btn-danger\" onclick=\"D.notes=D.notes.filter(x=>x.id!=="+n.id+");SD();RN();M()\">🗑</button></div></div>").join(""):"<div class=\"item empty\">📭 "+(CM?MEMBERS.find(m=>m.id===CM).name+" 暂无便签":"还没有便签")+"</div>"}
function handleFiles(files){let a=parseInt(document.getElementById("fileAuthor").value)||null;Array.from(files).forEach(f=>{let r=new FileReader();r.onload=e=>{D.files.unshift({id:Date.now()+Math.random(),name:f.name,size:f.size,type:f.type,data:e.target.result,authorId:a,ct:new Date().toLocaleString()});SD();RF();M()};r.readAsDataURL(f)});toast(files.length+" 文件已上传","success")}
function RF(){let items=D.files;if(CM)items=items.filter(x=>x.authorId===CM);let s=document.getElementById("fileSearch").value.toLowerCase();if(s)items=items.filter(f=>f.name.toLowerCase().includes(s));document.getElementById("fileList").innerHTML=items.length?items.map(f=>{let sz=f.size>1024?(f.size/1024).toFixed(1)+"KB":f.size+"B";return"<div class=\"item\"><div class=\"item-info\"><div class=\"item-title\">"+(f.type.match(/image/)?String.fromCodePoint(0x1F5BC):f.type.match(/video/)?String.fromCodePoint(0x1F3AC):String.fromCodePoint(0x1F4C4))+" "+f.name+"</div><div class=\"item-meta\">"+sz+" "+(f.authorId?"<span class=\"item-author\">"+MEMBERS.find(m=>m.id===f.authorId).name+"</span>":"")+" · "+f.ct+"</div></div><div class=\"item-actions\"><button class=\"btn btn-sm btn-outline\" onclick=\"downloadFile("+JSON.stringify(f.data)+","+JSON.stringify(f.name)+")\">⬇</button><button class=\"btn btn-sm btn-danger\" onclick=\"D.files=D.files.filter(x=>x.id!=="+f.id+");SD();RF();M()\">🗑</button></div></div>"}).join(""):"<div class=\"item empty\">📭 "+(CM?MEMBERS.find(m=>m.id===CM).name+" 暂无文件":"还没有文件")+"</div>"}
function downloadFile(d,n){let a=document.createElement("a");a.href=d;a.download=n;a.click()}
function addLink(){let t=document.getElementById("linkTitle").value.trim(),u=document.getElementById("linkUrl").value.trim(),a=parseInt(document.getElementById("linkAuthor").value)||null;if(!u){toast("请输入网址","error");return}let url=u.startsWith("http")?u:"https://"+u;D.links.unshift({id:Date.now(),title:t||url,url,authorId:a,ct:new Date().toLocaleString()});SD();document.getElementById("linkTitle").value="";document.getElementById("linkUrl").value="";RL();M();toast("已添加","success")}
function RL(){let items=D.links;if(CM)items=items.filter(x=>x.authorId===CM);let s=document.getElementById("linkSearch").value.toLowerCase();if(s)items=items.filter(l=>l.title.toLowerCase().includes(s)||l.url.toLowerCase().includes(s));document.getElementById("linkList").innerHTML=items.length?items.map(l=>"<a class=\"item\" href=\""+l.url+"\" target=\"_blank\" style=\"text-decoration:none;color:var(--text)\"><div class=\"item-info\"><div class=\"item-title\">🔗 "+l.title+"</div><div class=\"item-meta\">"+l.url.replace(/https?:\/\//,"").split("/")[0]+" "+(l.authorId?"<span class=\"item-author\">"+MEMBERS.find(m=>m.id===l.authorId).name+"</span>":"")+"</div></div><button class=\"btn btn-sm btn-danger\" onclick=\"event.preventDefault();event.stopPropagation();D.links=D.links.filter(x=>x.id!=="+l.id+");SD();RL()\">🗑</button></a>").join(""):"<div class=\"item empty\">🔗 "+(CM?MEMBERS.find(m=>m.id===CM).name+" 暂无链接":"还没有链接")+"</div>"}
function addTask(){let t=document.getElementById("taskTitle").value.trim(),a=parseInt(document.getElementById("taskAssignee").value)||null,p=document.getElementById("taskPriority").value;if(!t){toast("请输入任务","error");return}D.tasks.unshift({id:Date.now(),title:t,assigneeId:a,priority:p,done:false,ct:new Date().toLocaleString()});SD();document.getElementById("taskTitle").value="";RT();M();toast("已添加","success")}
let TF={assignee:null,priority:null,done:null}
function RT(){let items=D.tasks;if(CM)items=items.filter(x=>x.assigneeId===CM);if(TF.assignee)items=items.filter(t=>t.assigneeId===TF.assignee);if(TF.priority)items=items.filter(t=>t.priority===TF.priority);if(TF.done!==null)items=items.filter(t=>t.done===TF.done);items=[...items].sort((a,b)=>a.done-b.done);let pm={high:"🔴 高",medium:"🟡 中",low:"🟢 低"};document.getElementById("taskList").innerHTML=items.length?items.map(t=>{let a=MEMBERS.find(m=>m.id===t.assigneeId);return"<div class=\"item\" style=\""+(t.done?"opacity:.5":"")+"\"><div class=\"item-info\"><div style=\"display:flex;align-items:center;gap:6px\"><span style=\"cursor:pointer;font-size:18px\" onclick=\"TT("+t.id+")\">"+(t.done?"✅":"⬜")+'</span><span class="item-title" style="'+(t.done?"text-decoration:line-through":"")+'">'+t.title+'</span></div><div class="item-meta">'+pm[t.priority]+(a?" · <span class="item-author">"+a.name+"</span>":"")+" · "+t.ct+'</div></div><button class="btn btn-sm btn-danger" onclick="D.tasks=D.tasks.filter(x=>x.id!=='+t.id+');SD();RT();M()">🗑</button></div>'}).join(""):'<div class="item empty">✅ '+(CM?MEMBERS.find(m=>m.id===CM).name+" 暂无任务":"没有匹配任务")+'</div>';let ft=document.getElementById("taskFilters");ft.innerHTML='<span class="filter-tag '+(TF.done===null?"active":"")+'" onclick="TF.done=null;RT()">全部 ('+items.length+')</span><span class="filter-tag '+(TF.done===false?"active":"")+'" onclick="TF.done=false;RT()">待办 ('+items.filter(t=>!t.done).length+')</span><span class="filter-tag '+(TF.done===true?"active":"")+'" onclick="TF.done=true;RT()">已完成 ('+items.filter(t=>t.done).length+')</span>'+MEMBERS.map(m=>'<span class="filter-tag '+(TF.assignee===m.id?"active":"")+'" onclick="TF.assignee=TF.assignee===m.id?null:'+m.id+';RT()">'+m.name+'</span>')}
function TT(id){let t=D.tasks.find(t=>t.id===id);if(!t)return;t.done=!t.done;SD();RT();M();toast(t.done?"✅ 已完成":"🔄 已恢复","success")}
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".tab,.panel").forEach(el=>el.classList.remove("active"));tab.classList.add("active");document.getElementById("pn-"+tab.dataset.tab).classList.add("active")}))
let drop=document.querySelector(".file-drop-area");if(drop){drop.addEventListener("dragover",e=>{e.preventDefault();drop.style.borderColor="var(--accent2)"});drop.addEventListener("dragleave",()=>drop.style.borderColor="var(--border)");drop.addEventListener("drop",e=>{e.preventDefault();drop.style.borderColor="var(--border)";handleFiles(e.dataTransfer.files)})}
let WP=[{n:"深邃星空",t:"d",c:["#0f0f1a","#1a1a2e","#222250"]},{n:"暗夜紫",t:"d",c:["#0a0a14","#1a0a2e","#2a1a3e"]},{n:"石墨灰",t:"d",c:["#0e0e0e","#1a1a1a","#282828"]},{n:"深海蓝",t:"d",c:["#0a0e1a","#0f1a2e","#142842"]},{n:"暖阳橙",t:"w",c:["#1a1008","#2a1a0e","#3a2514"]},{n:"炭火红",t:"w",c:["#1a0808","#2e1212","#3e1a1a"]},{n:"琥珀金",t:"w",c:["#1a1208","#2a1c0e","#3a2614"]},{n:"落日霞",t:"w",c:["#1a0a10","#2e1420","#40202e"]},{n:"森林绿",t:"g",c:["#0a120c","#0e1e14","#142a1c"]},{n:"极光绿",t:"g",c:["#0a1410","#0a2a20","#0a3e30"]},{n:"苔藓青",t:"g",c:["#0a100a","#122012","#1a301a"]},{n:"海洋蓝",t:"g",c:["#0a0e18","#0c1e30","#102e48"]},{n:"樱花粉",t:"p",c:["#140a10","#241420","#341e30"]},{n:"丁香紫",t:"p",c:["#100a18","#1e1430","#2e1e44"]},{n:"薄荷青",t:"p",c:["#0a1412","#122422","#1a3430"]},{n:"雾霾蓝",t:"p",c:["#0e1018","#1a1e2e","#262e44"]},{n:"赛博紫",t:"c",c:["#080010","#1a0040","#2e0060"]},{n:"矩阵绿",t:"c",c:["#000a00","#001a08","#002e10"]},{n:"霓虹蓝",t:"c",c:["#000818","#001840","#002868"]},{n:"赛博橙",t:"c",c:["#140800","#2e1200","#481e00"]},{n:"萨摩耶白",t:"s",c:["#1a1814","#2a241e","#3a3028"]},{n:"微笑天使",t:"s",c:["#181614","#28221c","#383028"]},{n:"雪绒花",t:"s",c:["#181a18","#242824","#303630"]},{n:"暖绒杏",t:"s",c:["#1a1812","#2a241c","#3a3026"]},{n:"棉花糖",t:"s",c:["#18161a","#26222a","#342e3a"]},{n:"冰奶油",t:"s",c:["#141618","#202428","#2c3238"]}]
let wpBg=null
function CW(){wpBg=document.createElement("div");wpBg.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;z-index:0;pointer-events:none;transition:opacity .5s";document.body.prepend(wpBg)}
function AG(c){if(!wpBg)CW();wpBg.style.background="linear-gradient(135deg,"+c[0]+","+c[1]+","+c[2]+")";wpBg.style.opacity=".8"}
function RWG(ac){let g=document.getElementById("wpGrid"),items=ac&&ac!=="all"?WP.filter(w=>w.t===ac):WP;g.innerHTML=items.map(w=>"<div class=\"wp-opt\" onclick=\"AG("+JSON.stringify(w.c)+")\" style=\"background:linear-gradient(135deg,"+w.c[0]+","+w.c[1]+","+w.c[2]+")\"<span class=\"wp-opt-name\">"+w.n+"</span></div>").join("")}
function RWC(){let ts=[...new Set(WP.map(w=>w.t))],ns={d:"🌙 暗",w:"🔥 暖",g:"🌿 自然",p:"🌸 柔",c:"🤖 赛博",s:"🐕 萨摩耶"};document.getElementById("wpCats").innerHTML="<span class=\"filter-tag active\" onclick=\"RWG()\">全部</span>"+ts.map(t=>"<span class=\"filter-tag\" onclick=\"RWG('"+t+"')\">"+ns[t]+"</span>").join("")}
document.getElementById("wpBtn").addEventListener("click",()=>document.getElementById("wpPanel").classList.toggle("show"))
document.addEventListener("click",e=>{if(!e.target.closest(".wp-panel")&&!e.target.closest("#wpBtn"))document.getElementById("wpPanel").classList.remove("show")})
document.getElementById("wpFileInput").addEventListener("change",function(){if(this.files[0]){let r=new FileReader();r.onload=e=>{if(!wpBg)CW();wpBg.style.backgroundImage="url("+e.target.result+")";wpBg.style.backgroundSize="cover";wpBg.style.backgroundPosition="center"};r.readAsDataURL(this.files[0])}})

function setCM(i){CM=CM===i?null:i;M();RN();RF();RL();RT();var h1=document.querySelector(".header h1"),hp=document.querySelector(".header p");if(CM){var m=MEMBERS.find(function(x){return x.id===CM});hp.textContent=String.fromCodePoint(0x25B8)+" "+m.name+String.fromCodePoint(0x00B7)+m.role;h1.textContent=String.fromCodePoint(0x1F3E2)+" "+m.name+String.fromCodePoint(0x7684)+String.fromCodePoint(0x7A7A)+String.fromCodePoint(0x95F4)}else{hp.textContent=String.fromCodePoint(0x6218)+String.fromCodePoint(0x7565)+String.fromCodePoint(0x7EDF)+String.fromCodePoint(0x7B79)+String.fromCodePoint(0x00B7)+String.fromCodePoint(0x79D1)+String.fromCodePoint(0x7814)+String.fromCodePoint(0x5408)+String.fromCodePoint(0x89C4)+String.fromCodePoint(0x00B7)+String.fromCodePoint(0x5E02)+String.fromCodePoint(0x573A)+String.fromCodePoint(0x54C1)+String.fromCodePoint(0x724C)+String.fromCodePoint(0x00B7)+String.fromCodePoint(0x6E20)+String.fromCodePoint(0x9053)+String.fromCodePoint(0x8FD0)+String.fromCodePoint(0x8425)+String.fromCodePoint(0x00B7)+String.fromCodePoint(0x8D22)+String.fromCodePoint(0x52A1)+String.fromCodePoint(0x8DEF)+String.fromCodePoint(0x6F14);h1.textContent=String.fromCodePoint(0x1F3E2)+String.fromCodePoint(0x4E94)+String.fromCodePoint(0x4EBA)+String.fromCodePoint(0x534F)+String.fromCodePoint(0x4F5C)+String.fromCodePoint(0x00B7)+String.fromCodePoint(0x5171)+String.fromCodePoint(0x4EAB)+String.fromCodePoint(0x7A7A)+String.fromCodePoint(0x95F4)}}
var WK="wp_";function gk(){return WK+(CM||"default")}function lp(){try{var v=localStorage.getItem(gk());if(v){var d=JSON.parse(v);if(d.t==="g"){AG(d.c);return}}}catch(e){}AG(WP[20].c)}function sp(c){try{localStorage.setItem(gk(),JSON.stringify({t:"g",c:c}))}catch(e){}}
function RWG(ac){var g=document.getElementById("wpGrid");var items=ac&&ac!=="all"?WP.filter(function(w){return w.t===ac}):WP;g.innerHTML=items.map(function(w){return"<div class=\"wp-opt\" onclick=\"AG("+JSON.stringify(w.c)+");sp("+JSON.stringify(w.c)+");document.getElementById('wpPanel').classList.remove('show')\" style=\"background:linear-gradient(135deg,"+w.c[0]+","+w.c[1]+","+w.c[2]+")\"><span class=\"wp-opt-name\">"+w.n+"</span></div>"}).join("")}
CW();lp();RWG();RWC();LD();PS();M();RN();RF();RL();RT()